# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa819a40a0f532c37b5136cacf53f9c789a15d3abd351d5e67672dbd58ed5feac02c08fba0d9806913edf175ae509c62cc0d6b890715c645c37b0546cd1defd3

test:
  secret_key_base: 435b85f319baf5ef7b4ccb1b6096f57fd569feb169e2af4f53be73ab1969ec531310637bdff04d5bc84d741376563758605141107942d14e4d1fe8c92841f8f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
